# START: initial
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "proglog.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{ include "proglog.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "proglog.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "proglog.fullname" . }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      name: {{ include "proglog.fullname" . }}
      labels: {{ include "proglog.labels" . | nindent 8 }}
    spec:
      # initContainers...
      # END: initial
      # START: initial_containers
      initContainers:
      - name: {{ include "proglog.fullname" . }}-config-init
        image: busybox
        imagePullPolicy: IfNotPresent
        command:          
          - /bin/sh
          - -c
          - |-
            ID=$(echo $HOSTNAME | rev | cut -d- -f1 | rev)
            cat > /var/run/proglog/config.yaml <<EOD
            data-dir: /var/run/proglog/data
            rpc-port: {{.Values.rpcPort}}
            bind-addr: \
              "$HOSTNAME.proglog.{{.Release.Namespace}}.\svc.cluster.local:\
                {{.Values.serfPort}}"
            $([ $ID != 0 ] && echo 'start-join-addrs: \
              "proglog-0.proglog.{{.Release.Namespace}}.svc.cluster.local:\
                {{.Values.serfPort}}"')
            bootstrap: $([ $ID = 0 ] && echo true || echo false )            
            EOD   
        volumeMounts:
        - name: datadir
          mountPath: /var/run/proglog
        # START: initial
      # END: initial_containers
      # START: initial
      # containers...
      # END: initial
      # START: containers
      containers:
      - name: {{ include "proglog.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.rpcPort }}
          name: rpc
        - containerPort: {{ .Values.serfPort }}
          name: serf
        args:
          - --config-file=/var/run/proglog/config.yaml
        # END: initial
        # probes...
        # END: containers
        # START: probes
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.rpcPort }}"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:{{ .Values.rpcPort }}"]
          initialDelaySeconds: 10
        # END: probes
        # START: containers
        volumeMounts:
        - name: datadir
          mountPath: /var/run/proglog
      # END: containers
      # START: initial
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.storage }}
